A = imread('soccer_4.png');
figure;
R = A(:,:,1);
G = A(:,:,2);
B = A(:,:,3);
indices = logical(G>R) & logical(R>B);
out = uint8(1-indices) * 255;
imshow(out);
edgeA = 255*uint8(edge(rgb2gray(A),'Sobel',0.05));
pause(1);imshow(edgeA);
out = max(out,edgeA);
pause(1);imshow(out);
out = bwmorph(out,'branchpoints');
pause(1);imshow(out);
out = imclose(out,strel('diamond',5));
pause(1);imshow(out);
out = imopen(out,strel('disk',3));
pause(1);imshow(out);
out = bwmorph(out,'clean',Inf);
pause(1);imshow(out);
BW = im2bw(out);
BW2 = bwareafilt(BW,1);
BW(BW2) = 0;
imshow(BW);
figure,imshow(A);